### ISSUE TITLE
建议增加AccessToken的配置入口

### ISSUE THREAD

**Issue by sdlyfjx** [pengng/wechat-open-toolkit#2]
目前的ticket，AccessToken等通过服务启动后存储在临时变量里进行维护，这样无法适用于类似Serverless架构下使用（无状态、自伸缩）

可以增加放到redis或者其他db中进行维护。或直接实现一个接口，传入自定义的获取方法

**Comment by pengng** [comment]
@sdlyfjx 目前不确定该应用适合 Serverless 架构。可能改成 Serverless 架构后复杂度提高，带来的收益却并不大。

**Comment by pengng** [comment]
@sdlyfjx 感谢你的建议。

**Comment by sdlyfjx** [comment]
好滴~~~~
